spring: #띄어쓰기 없음
  datasource: #띄어쓰기 2칸
    url: jdbc:h2:tcp://localhost/~/board #4칸
    username: sa
    password:
    driver-class-name: org.h2.Driver

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa: #띄어쓰기 2칸
    hibernate: #띄어쓰기 4칸
      ddl-auto: create #띄어쓰기 6칸
    properties: #띄어쓰기 4칸
      hibernate: #띄어쓰기 6칸
        # show_sql: true #띄어쓰기 8칸
        format_sql: true #띄어쓰기 8칸

  mvc:
    hidden-method:
      filter:
        enabled: true

  devtools:
    livereload:
      enabled: true
    thymeleaf:
      cache: false
    restart:
      enable: false #운영에서는 제거

logging:
  level: #띄어쓰기 없음
    org.hibernate.SQL: debug #띄어쓰기 2칸

upload:
  path: C:/study/file/

